# B매장 설정 (실제 테스트 검증 완료)
store:
  id: "B"
  name: "B매장"
  website_url: "https://a15878.parkingweb.kr/login"
  
login:
  username: "215"
  password: "4318"

# 쿠폰 타입 매핑 (실제 확인된 타입)
# B 매장 특수사항: 주말 전용 쿠폰 없음, 무료 쿠폰 항상 보유
coupons:
  FREE_1HOUR:
    name: "무료 1시간할인"
    type: "free"
    duration_minutes: 60
    priority: 0
  PAID_30MIN:
    name: "유료 30분할인 (판매 : 300 )"
    type: "paid"
    duration_minutes: 30
    priority: 1
  # WEEKEND 타입 쿠폰 없음 - 주말에도 PAID 타입 사용

# 할인 정책
discount_policy:
  weekday:
    target_hours: 3
    max_coupons: 6
  weekend:
    target_hours: 2
    max_coupons: 4

# 웹 셀렉터 (실제 테스트로 검증된 셀렉터)
selectors:
  # 로그인 관련 (실제 확인됨 - Playwright MCP 테스트 기준)
  login:
    username_input: 'textbox[name="ID"]'  # 실제 동작: getByRole('textbox', { name: 'ID' })
    password_input: 'textbox[name="PASSWORD"]'  # 실제 동작: getByRole('textbox', { name: 'PASSWORD' })
    login_button: 'button[name="Submit"]'  # 실제 동작: getByRole('button', { name: 'Submit' })
    login_success_indicator: 'text=사용자'  # 로그인 후 "215(이수열) - 사용자" 텍스트
  
  # 팝업 처리
  popups:
    notice_popup: 'text=안내'
    ok_button: 'text=OK'
  
  # 차량 검색 (실제 확인됨)
  search:
    car_number_input: 'textbox[name="차량번호"]'  # 실제: getByRole('textbox', { name: '차량번호' })
    search_button: 'button[name="검색"]'  # 실제: getByRole('button', { name: '검색' })
    no_result_message: 'text=검색 결과가 없습니다'  # 실제 메시지
    search_result_table: 'table'  # 검색 결과 테이블
  
  # 쿠폰 관련 (할인등록현황 페이지에서 확인)
  coupons:
    discount_type_dropdown: 'combobox'  # 할인 유형 드롭다운
    discount_list: "ul.discount-list"  # 추정 - 실제 차량 선택 후 확인 필요
    discount_items: "ul.discount-list li"  # 추정 - 실제 차량 선택 후 확인 필요  
    apply_button: ".apply-discount-btn"  # 추정 - 실제 차량 선택 후 확인 필요
  
  # 페이지 URL
  urls:
    login: "/login"
    discount_registration: "/discount/registration"
    discount_status: "/state/doViewMst"
    discount_purchase: "/pay/doViewDscnt" 